[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.5.1", features = ["csr"] }
web-sys = "0.3.64"
leptonic = { git = "https://github.com/lhjok/leptonic"} # Until leptonic is officially compatible with leptos 0.5
#leptonic = "0.2.0"
leptos-use = "0.7.1"
cubelib = { path = "../cubelib", features = ["cube"]}
cubelib-interface = { path = "../interface" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }

[build-dependencies]
leptonic-theme = "0.2.0"
leptos-tiptap-build = "0.2.3"
