[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.5.1", features = ["csr"] }
web-sys = "0.3.64"
wasm-bindgen = {version = "0.2.87"}
leptonic = "0.2.0"

[build-dependencies]
leptonic-theme = "0.2.0"
leptos-tiptap-build = "0.2.3"
