[package]
name = "cubelib"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
log = "0.4.20"
simple_logger = "4.2.0"
clap = { version = "4.3.15", features = ["derive"] }

#[lib]
#crate-type = ["cdylib", "rlib"]
