[build]
#rustflags = "-C target-feature=+avx2"
#target = "wasm32-unknown-unknown"

rustflags = "-C target-feature=+avx2"

[target.aarch64-apple-darwin]
rustflags = "-C target-feature=+neon"
linker = "rust-lld"

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"