[package]
name = "cubelib"
version = "1.2.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
log = "0.4.20"
simple_logger = "4.2.0"
#web-sys = "0.3.64"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["cube"]
cube = []
solver = ["cube"]
