[package]
name = "cubelib"
version = "1.2.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
log = "0.4.20"
simple_logger = "4.2.0"
serde = { version = "1.0.190", optional = true, features = ["derive"] }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["cube", "default_solver"]
cube = []
solver = ["cube"]
default_solver = ["cube", "solver", "step_eo", "step_dr", "step_htr", "step_fr", "step_finish"]
step_eo = ["cube", "solver"]
step_dr = ["step_eo", "solver"]
step_htr = ["step_dr", "solver"]
step_fr = ["step_htr", "solver"]
step_finish = ["step_fr", "solver"]
serde_support = ["dep:serde"]