[package]
name = "cubelib"
version = "1.2.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
log = "0.4.20"
simple_logger = "4.2.0"
serde = { version = "1.0.190", optional = true, features = ["derive"] }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
solver = []
cubic = []
cubic-even = ["cubic"]
cubic-odd = ["cubic"]

default = ["333", "222", "pyraminx"]

222 = ["cubic-even"]
222finish = ["222", "solver"]

333 = ["cubic-odd"]
333eo = ["333", "solver"]
333dr = ["333eo"]
333htr = ["333dr"]
333fr = ["333htr"]
333finish = ["333fr"]

pyraminx = []

serde_support = ["dep:serde"]