[build]
rustflags = "-C target-feature=+avx2"

[target.aarch64-apple-darwin]
rustflags = "-C target-feature=+neon"
linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
rustflags = "-C target-feature=+neon"
linker = "rust-lld"

[target.aarch64-unknown-linux-gnu]
rustflags = "-C target-feature=+neon"

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
