main = _{ SOI ~ (sequence | parallel | group) ~ EOI }

group = _{ step | "(" ~ sequence ~ ")" | "(" ~ parallel ~ ")" }

sequence = { group ~ (">" ~ group)+ }
parallel = { group ~ ("|" ~ group)+ }

step = { name ~ ("[" ~ parameters ~ "]")?}
name = { ASCII_ALPHA+ }
parameters = _{ parameter ~ (";" ~ parameter)* }
parameter = _{ key ~ "=" ~ value | variant }
key = { ASCII_ALPHA+ }
variant = { ASCII_ALPHA+ }
value = { (ASCII_ALPHANUMERIC | "," | "'" | " ")+ }

WHITESPACE = _{ " " }